version: '3'
services:
  db-cats-api:
    image: postgres:15
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cats_api_db