apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-api
  labels:
    app: cats-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats-api
  template:
    metadata:
      labels:
        app: cats-api
    spec:
      containers:
        - name: cats-api
          image: olejatorqq/cats-api:1.0.0
          ports:
            - containerPort: 8765
          env:
            - name: DATASOURCE_HOST
              value: 192.168.1.108
            - name: spring.mvc.servlet.path
              value: /cats-api